### ISSUE TITLE
README.md outdated

### ISSUE THREAD

**Issue by JapuDCret** [radcortez/flyway-junit5-extensions#138]
The examples seem to be outdated.

E.g. in the meta annotations section
```java
@FlywayTest(datasource = @Datasource(url = "jdbc:h2:mem:test"))
```
does not longer work, but
```java
@FlywayTest(@DataSource(url = "jdbc:h2:mem:test"))
```
(big S in DataSource and omitted `datasource = `)

**Comment by radcortez** [comment]
Thanks, I've updated the README to align with the API: https://github.com/radcortez/flyway-junit5-extensions/commit/6c4159cccf74288dd8e81d5341adec78ae1aa7be

Sorry for the inconvenience.
