### ISSUE TITLE
Investigate support for JUnit @Nested

### ISSUE THREAD

**Issue by radcortez** [radcortez/flyway-junit5-extensions#143]

**Comment by overheadhunter** [comment]
To add some context:

JUnit 5 adds support for an arbitrary amount of `@Nested` tests. Currently, the Flyway migration scripts will only run for _direct_ members of the annotated class:

```java
@FlywayTest(...)
class Test {

    @Test
    public void test1() { ... } // ✔︎

    @Nested
    public class Nested1 {

        @Test
        public void test2() { ... } // ✘

    }

    @Nested
    @FlywayTest(...)
    public class Nested2 {

        @Test
        public void test3() { ... } // ✔︎

    }

}
```

I would expect nested test classes to inherit the behaviour from their parent. That said, it should be possible to overwrite behaviour in nested classes (i.e. setting `clean = false` for nested class that has an `@Order`ed sequence of tests)

**Comment by radcortez** [comment]
Thanks. I'll have a look.

**Comment by radcortez** [comment]
@overheadhunter any chance for you to try out #147?

The `@FlywayTest` behaviour is always a merge of all metadata across the hierarchy (or enclosing class). 

For instance, if a parent class is annotated with `clean = false`, all nested classes also inherit the same behaviour. If a nested class overrides `clean = true`, it applies only in the context of that nested class.

**Comment by overheadhunter** [comment]
On first glance that seems to work. 🙌 

However, Quarkus is giving me a hard time testing _multiple levels_ of nested tests. So I can not really verify this case.

**Comment by radcortez** [comment]
Ok, thanks. I'll do a release as is, and then we will try to figure out on the Quarkus side.
