### ISSUE TITLE
How to use this extension with a database managed by Quarks Dev Services 

### ISSUE THREAD

**Issue by jorgebsa** [radcortez/flyway-junit5-extensions#173]
In the Quarkus example implementation of the `DataSourceProvider` you make it clear that it's not possible to interact with Quarkus at that point in order to get the connection string directly from `ConfigProvider.getConfig()`, so you rely on reading the `application.properties` file with the help of `SmallRyeConfigBuilder`.

My question is: since the value of `quarkus.datasource.jdbc.url` is purposely omitted from the file in order to have the DB launched by Dev Service during test, how would you be able to get the connection details in order to implement a `DataSourceProvider` ? 

There's probably a way of doing so, but I'm quite new to the Quarkus world so I'm not aware. Really need this for my integration tests, or else I will have to rely on dropping and populating everything manually for each test, which is quite tedious and error-prone

**Comment by radcortez** [comment]
DevServices were added after I wrote this extension, so I never fully integrated them. The plan was to bring in this extension natively into Quarkus, but I haven't got the time to do it: https://github.com/quarkusio/quarkus/issues/14240

Anyway, let me see if I can at least come up with something to integrate with DevServices.

**Comment by jorgebsa** [comment]
Totally understandable :) here's to hoping you are able to figure something in order to make it work with dev services haha

**Comment by radcortez** [comment]
Hi @jorgebsa, check #175 on how to do it.

**Comment by jorgebsa** [comment]
will try it out later, much appreciated 🥳

**Comment by jorgebsa** [comment]
Just to let you know, testes it against quarkus 2.6.3 and it works as expected :) thank you so much for the implementing the solution so quickly, much appreciated
