### ISSUE TITLE
Quarkus native test

### ISSUE THREAD

**Issue by carlosthe19916** [radcortez/flyway-junit5-extensions#74]
First of all, thanks for creating this extension it is very useful when creating tests.

Rather than asking for a solution, I'd like to understand if you have ever tried to use your extension in native mode

```java
import io.quarkus.test.junit.NativeImageTest;

@NativeImageTestpublic
class NativeFruitsEndpointIT extends FruitsEndpointTest {
    // Runs the same tests as the parent class
}
```

Just like all the examples in Quarkus-quickstart e.g. https://github.com/quarkusio/quarkus-quickstarts/blob/main/hibernate-orm-panache-quickstart/src/test/java/org/acme/hibernate/orm/panache/NativeFruitsEndpointIT.java

- I've tried to execute a native test using Quarkus with no success, it seems that in native mode the extension is not executed. However, all tests in no native mode work perfectly fine. Is this an expected behavior or perhaps the extension requires enhancement for Quarkus Native tests?

**Comment by radcortez** [comment]
Hi @carlosthe19916,

Thanks for the report. I've never tried this with native. I'll need to have a look. It theory it should be possible, but with some limitations (H2 server doesn't work in native for instance).

**Comment by radcortez** [comment]
Hi @carlosthe19916,

I've added an example in #77. Please, check it out.

**Comment by carlosthe19916** [comment]
Awesome! Thank you very much @radcortez
